# this is an example configuration file, you will need to 
# create your own config.toml file

[prometheus]
ip = "127.0.0.1 # IP adress of the promethus server
port = 9090 # Standard port for promethus api
fetchInterval = 10000 # 10 seconds is standard for promethus

